# Memory size = 128 words denoted by 7 bits
# Number of blocks = 32 addressed by 5 bits of block number
# Words per block = 4 selected using block offset of 2 bits

# Cache size = 16 words total
# Number of lines = 4 
# 1 block per line i.e. 4 words per line

In [148]:
import numpy as np

# Initial conditions

In [209]:
cache = [np.array([int, np.empty(4), int], dtype=object), 
         np.array([int, np.empty(4), int], dtype=object), 
         np.array([int, np.empty(4), int], dtype=object), 
         np.array([int, np.empty(4), int], dtype=object)] 
mem = [[0]*4 for x in range(32)]

global cache_counter
cache_counter = 0

# Separate block number and block offset

In [104]:
def partition(i):
    b_offset = int("{:02d}".format(i%100))
    b_no = int(i / 100)
    return b_no, b_offset

# Check cache for hit or miss indicated by valid bit. 
If valid = 1 => hit, if valid = 0 => miss

In [246]:
def check_cache(b_no, b_offset):
    global cache_counter
    valid = 0
    
    for i in range(4): #Check for hit or miss
        if cache[i][0] == b_no:
            valid = 1
            break
        else:
            valid = 0
            
    if(valid): #hit
        print(f"Data: {cache[i][1][b_offset]}")
        cache[i][2] += 1
    else: #miss
        if(cache_counter <= 3):
            cache[cache_counter][0] = b_no
            cache[cache_counter][1] = mem[block_number]
            cache[cache_counter][2] = 0
            cache_counter += 1
            print(f"Data: {mem[b_no][b_offset]}")
        else:
            lowest_priority = min(cache[0][2], cache[1][2], cache[2][2], cache[3][2])
            for i in range(4):
                if(cache[i][2] == lowest_priority):
                    cache[i][0] = b_no
                    cache[i][1] = mem[block_number]
                    cache[i][2] = 0
                    break
            
    return int(valid)

# Main function

In [247]:
while(1):
    print("Enter 1 for read, 0 for write and q to exit: ")
    temp = input()
    if(temp == 'q'): # Quit Condition
        break
    else:
        rw = int(temp)
        print("Enter memory address: ")
        i = int(input())
        block_number, block_offset = partition(i)
        block_number = int(str(block_number), 2)
        block_offset = int(str(block_offset), 2)
#         print(f"block_number: {block_number}")
#         print(f"block_offset: {block_offset}")
        
        if(rw): # Read Operation
            hit = check_cache(block_number, block_offset)
            print(f"Hit/Miss: {hit}")
        else: # Write Operation
            print("Enter data: ")
            data = int(input())
            mem[block_number][block_offset] = data

Enter 1 for read, 0 for write and q to exit: 


 1


Enter memory address: 


 0000010


Data: 42
Hit/Miss: 1
Enter 1 for read, 0 for write and q to exit: 


 q


# Debug

In [243]:
mem

[[0, 0, 42, 0],
 [69, 0, 0, 0],
 [0, 0, 0, 70],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 25, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [25, 0, 0, 50],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0]]

In [240]:
cache

[array([18, list([25, 0, 0, 50]), 2], dtype=object),
 array([0, list([0, 0, 42, 0]), 0], dtype=object),
 array([8, list([0, 0, 25, 0]), 1], dtype=object),
 array([1, list([69, 0, 0, 0]), 1], dtype=object)]

In [241]:
cache_counter

4